Task/1 unittest file util solution
dewll/tasks pull request #2
Opened 2022-04-19 22:22 UTC by dewll

2022-04-20 18:52 UTC, co-admin requested changes

2022-04-20 18:52 UTC, co-admin commented on task1_solution/src/file.ts
> +import * as os from 'os';
@dewll move to the `utils` folder where is initial file, so we can check what have been changed there.

2022-04-20 18:52 UTC, co-admin commented on task1_solution/tests/file.spec.ts
> +describe('File', ()=>{
Call it FileUtils (better to use class name in describe).

2022-04-20 18:52 UTC, co-admin commented on task1_solution/tests/file.spec.ts
> +        });
Run `npm run lint -- --fix` and autolint your code.

2022-04-20 18:52 UTC, co-admin commented on task1_solution/tests/file.spec.ts
> +        const downloadTempFile = FileUtils.downloadTempFile('https://www.google.com/', `${os.tmpdir()}/${folderPath}/${fileName}`)
`${os.tmpdir()}/${folderPath}/${fileName}` - you copy pasted it across the whole test, better to move in const or private function.

2022-04-20 18:52 UTC, co-admin commented on task1_solution/tests/file.spec.ts
> +        });
@dewll add also failed scenarios, when for instance we try to remove not existing file, or get folder which is not existing, write empty/undefined data

2022-04-20 18:53 UTC, co-admin commented
Let me know if you have questions

2022-04-20 22:34 UTC, dewll commented on task1_solution/src/file.ts
> +import * as os from 'os';
Ok

2022-04-20 22:34 UTC, dewll commented on task1_solution/tests/file.spec.ts
> +describe('File', ()=>{
Ok

2022-04-20 22:34 UTC, dewll commented on task1_solution/tests/file.spec.ts
> +        });
Ok

2022-04-20 22:35 UTC, dewll commented on task1_solution/tests/file.spec.ts
> +        const downloadTempFile = FileUtils.downloadTempFile('https://www.google.com/', `${os.tmpdir()}/${folderPath}/${fileName}`)
Ok, I will correct it

2022-04-20 22:35 UTC, dewll commented on task1_solution/tests/file.spec.ts
> +        });
Ok

2022-04-21 11:11 UTC, dewll commented
i have make some correction on it

2022-04-21 15:52 UTC, co-admin commented on task1_solution/src/file.ts
> +function removeDir(dirPath: string): Promise<void> {
@dewll do you understand why we don't need to use here `async function` and don't why don't we use await `fs.emptyDir()`?

2022-04-21 15:54 UTC, co-admin commented on task1_solution/src/file.ts
> +  tempFileFinder,
move the method to the top, so it follow order.

2022-04-21 15:54 UTC, co-admin commented on task1_solution/src/file.ts
> +  const tempFilePath = path.join(os.tmpdir(), ...components);
@dewll use here `tempFileFinder()` to be sure that we use single source of truth.

2022-04-21 15:55 UTC, co-admin commented on task1_solution/src/file.ts
> +  if (!tempFilePath.includes(os.tmpdir())) {
same here

2022-04-21 16:43 UTC, dewll commented on task1_solution/src/file.ts
> +function removeDir(dirPath: string): Promise<void> {
We don't need to use async function, because the function call is perfoming a simple task, which does not involve complex task that is going to take alot of time before it finished it.
likewise for fs.emptyDir() we don't need to use await because is not returnning anything

2022-04-21 22:58 UTC, dewll commented on task1_solution/src/file.ts
> +  const tempFilePath = path.join(os.tmpdir(), ...components);
Done

2022-04-21 22:58 UTC, dewll commented on task1_solution/src/file.ts
> +  if (!tempFilePath.includes(os.tmpdir())) {
Done

2022-04-21 22:59 UTC, dewll commented on task1_solution/src/file.ts
> +  if (dirPath.includes(os.tmpdir())) {
Done

2022-04-27 12:15 UTC, co-admin approved these changes

2022-04-27 12:15 UTC, merged